version: "3.3"

services:
  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    image: otot-a1-app
    container_name: otot-a1-app
    ports:
      - "3000:8080"

  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: otot-a1-reverse-proxy
    container_name: otot-a1-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - app
