version: "3.3"

services:
  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "3000:8080"

  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
